# OMNI AGENT STACK - Promtail Configuration
# Secret Technique: Use Docker service discovery to automatically scrape logs from all containers.

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    # Secret Technique: The docker_sd_config discovers all running containers on the same host.
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    # Secret Technique: Relabeling is used to enrich logs with metadata from Docker labels.
    # This allows for powerful filtering and querying in Grafana.
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
