# OMNI AGENT STACK - Continuous Integration Workflow
# Secret Technique: Matrix builds and parallel execution.
# This workflow runs tests and builds for all services in parallel, providing rapid feedback.

name: OMNI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: "Lint & Format Check"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Placeholder for linting Go
      - name: Lint Go
        run: echo "Linting Go services..." # Add golangci-lint step here

      # Placeholder for linting Svelte
      - name: Lint Svelte
        run: |
          cd webui
          npm install
          npm run check

  test-and-build:
    name: "Test & Build Services"
    runs-on: ubuntu-latest
    # Secret Technique: Use a matrix strategy to run jobs for each service in parallel.
    strategy:
      matrix:
        service: [api_gateway, orchestrator, agent_template, webui]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        if: matrix.service != 'webui'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Node.js
        if: matrix.service == 'webui'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Go Service
        if: matrix.service != 'webui'
        run: |
          cd services/${{ matrix.service }}
          go build -v .

      - name: Test Go Service
        if: matrix.service != 'webui'
        run: |
          cd services/${{ matrix.service }}
          go test -v ./...

      - name: Build WebUI
        if: matrix.service == 'webui'
        run: |
          cd webui
          npm install
          npm run build

  build-docker-images:
    name: "Build Docker Images"
    runs-on: ubuntu-latest
    needs: [lint, test-and-build] # This job runs only if previous jobs succeed
    strategy:
      matrix:
        service: [api_gateway, orchestrator, webui] # Add other services with Dockerfiles
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service == 'webui' && './webui' || format('./services/{0}', matrix.service) }}
          file: ${{ matrix.service == 'webui' && './webui/Dockerfile' || format('./services/{0}/Dockerfile', matrix.service) }}
          push: false # Don't push images on CI for PRs
          tags: omni-${{ matrix.service }}:latest