# OMNI AGENT STACK - Grafana Datasource Provisioning
# Secret Technique: Automatic provisioning of datasources.
# On startup, Grafana will automatically configure Prometheus and Loki without manual setup.

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
